# Generated by Django 2.2.1 on 2019-07-17 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='course')),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineCourseApp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(max_length=30)),
                ('nationalCode', models.CharField(max_length=10)),
                ('date_signup', models.DateField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('last_education_level', models.CharField(choices=[['Diploma', 'Diploma'], ['Bachelor', 'Bachelor'], ['Master', 'Master'], ['PhD', 'PhD']], max_length=8)),
                ('last_education_university', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocket_money', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registration', models.DateField(default=django.utils.timezone.now)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='OnlineCourseApp.Course')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='OnlineCourseApp.Student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='Course',
            field=models.ManyToManyField(through='OnlineCourseApp.StudentCourse', to='OnlineCourseApp.Course'),
        ),
        migrations.AddField(
            model_name='student',
            name='CustomUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='OnlineCourseApp.CustomUser'),
        ),
        migrations.CreateModel(
            name='InstructorCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='OnlineCourseApp.Course')),
                ('Instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='OnlineCourseApp.Instructor')),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='Course',
            field=models.ManyToManyField(through='OnlineCourseApp.InstructorCourse', to='OnlineCourseApp.Course'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='CustomUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='OnlineCourseApp.CustomUser'),
        ),
    ]
