# Generated by Django 2.2.1 on 2019-07-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineCourseApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='CustomUser',
            new_name='customUser',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='CustomUser',
            new_name='customUser',
        ),
    ]
